name: neelkamath
description: Neel Kamath's personal website
author: Neel Kamath <neelkamath@icloud.com>
homepage: https://github.com/neelkamath/neelkamath.github.io

dev_dependencies:
  link_checker: ^2.0.1
  test: ^1.3.0

environment:
  sdk: '>=2.1.0 <3.0.0'
